name: Check code style

on: [push]

jobs:
  check-line-endings:
    name: Line endings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v2

      - name: Check line endings
        uses: AODocs/check-eol@main

  check-python-code-style:
    name: Python code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install black flake8 mypy

      - name: Check flake8 compliance
        run: flake8

      - name: Check Black compliance
        run: black --check .

      - name: Check mypy compliance
        run: mypy

  check-js-code-style:
    name: Check JavaScript code style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd frontend
        npm install prettier

    - name: Check Prettier compliance
      run: |
        cd frontend
        npx prettier --check src
        npx prettier --check pages
